name: one_ruku_daily
description: Read as little as one Ruku from the Quran daily
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: 3.22.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  collection: ^1.18.0
  cupertino_icons: ^1.0.6
  fl_chart: ^0.68.0
  flutter_bloc: any
  flutter_colorpicker: ^1.1.0
  flutter_local_notifications: ^17.0.1
  flutter_timezone: ^1.0.8
  hive_flutter: any
  hive: any
  intl: ^0.19.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  timezone: ^0.9.2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  hive_generator: any
  build_runner: ^2.1.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/metadata.json
    - assets/data/sura_ruku_map.json
    - assets/data/q-simple/
    - assets/l10n/

  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri/Amiri-Regular.ttf
    # - family: Baloo_Bhaijaan
    #   fonts:
    #     - asset: assets/fonts/Baloo_Bhaijaan/BalooBhaijaan-Regular.ttf
    # - family: Cairo
    #   fonts:
    #     - asset: assets/fonts/Cairo/Cairo-Regular.ttf
    # - family: Changa
    #   fonts:
    #     - asset: assets/fonts/Changa/Changa-Regular.ttf
    - family: El_Messiri
      fonts:
        - asset: assets/fonts/El_Messiri/ElMessiri-Regular.ttf
    - family: Harmattan
      fonts:
        - asset: assets/fonts/Harmattan/Harmattan-Regular.ttf
    - family: Jomhuria
      fonts:
        - asset: assets/fonts/Jomhuria/Jomhuria-Regular.ttf
    - family: Katibeh
      fonts:
        - asset: assets/fonts/Katibeh/Katibeh-Regular.ttf
    # - family: Lalezar
    #   fonts:
    #     - asset: assets/fonts/Lalezar/Lalezar-Regular.ttf
    - family: Lateef
      fonts:
        - asset: assets/fonts/Lateef/LateefRegOT.ttf
    # - family: Lemonada
    #   fonts:
    #     - asset: assets/fonts/Lemonada/Lemonada-Regular.ttf
    - family: Mirza
      fonts:
        - asset: assets/fonts/Mirza/Mirza-Regular.ttf
    # - family: Mada
    #   fonts:
    #     - asset: assets/fonts/Mada/Mada-Regular.ttf
    # - family: Markazi_Text
    #   fonts:
    #     - asset: assets/fonts/Markazi_Text/MarkaziText-Regular.ttf
    # - family: Rakkas
    #   fonts:
    #     - asset: assets/fonts/Rakkas/Rakkas-Regular.ttf
    # - family: Reem_Kufi
    #   fonts:
    #     - asset: assets/fonts/Reem_Kufi/ReemKufi-Regular.ttf
    - family: Scheherazade
      fonts:
        - asset: assets/fonts/Scheherazade/Scheherazade-Regular.ttf
    - family: p117
      fonts:
        - asset: assets/fonts/p117/p117.woff2
