name: one_ruku_daily
description: Read as little as one Ruku from the Quran daily
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: 3.22.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: any
  flutter_local_notifications: ^17.0.1
  hive_flutter: any
  hive: any
  permission_handler: ^11.3.1
  timezone: ^0.9.2
  intl: ^0.19.0
  collection: ^1.18.0
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  hive_generator: any
  build_runner: ^2.1.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/metadata.json
    - assets/data/q-simple/
    - assets/l10n/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
    - family: Lateef
      fonts:
        - asset: assets/fonts/Lateef/LateefRegOT.ttf
    - family: Katibeh
      fonts:
        - asset: assets/fonts/Katibeh/Katibeh-Regular.ttf
    - family: Mirza
      fonts:
        - asset: assets/fonts/Mirza/Mirza-Regular.ttf
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri/Amiri-Regular.ttf
